__contents:__

1. [Geometric transformations](#Geometric_transformations)
   * 1.1.[Image translation](#Image_translation)
   * 1.2.[Rotation](#Rotation)
   * 1.3.[Scaling](#Scaling)
   * 1.4.[Flipping](#Flipping)
   * 1.5.[Shearing](#Shearing)
   * 1.6.[Cropping](#Cropping)
2. [Arithmetic Operations](#Arithmetic_Operations)
   * 2.1.[Addition](#Addition)
     - 2.1.1.[weighted addition](#weighted_addition)
   * 2.2.[Subtraction](#Subtraction)
   * 2.3.[Multiplication and division](#Multi_division)
   * 2.4.[Bitwise operations](#Bitwise_operations)
     - 2.4.1.[AND](#AND)
     - 2.4.2.[OR](#OR)
     - 2.4.3.[XOR](#XOR)
     - 2.4.4.[NOT](#NOT)
   * 2.5.[Channels and color spaces](#ChannelsColorCpaces)
     - 2.5.1.[Red Green Blue (RGB) color space](#RGB)
     - 2.5.2.[Blue Green Red (BGR) color space](#BGR)
     - 2.5.3.[Hue Saturation Value (HSV) color space](#HSV)
     - 2.5.4.[Hue Saturation Lightness (HSL) color space](#HSL)
     - 2.5.5.[LAB color space](#LAB)
     - 2.5.6.[YCbCr color space](#YCbCr)
     - 2.5.7.[Grayscale](#Grayscale)

# <h2 style="color: blue;"> 1.Geometric transformations <a id='Geometric_transformations'></a></h2>

<font color='#808080'>
In technical terms, image processing involves transforming the coordinates of image points from one coordinate system to another. Using various transformation functions, it is possible to map pixel coordinates in the original image to new coordinates in the transformed image, resulting in different types of transformations.

As we move forward with this chapter, we will explore various image transformation techniques, including rotation, scaling, and more, beginning with image translation.

## <h2 style="color: blue;"> 1.1.Image translation <a id='Image_translation'></a></h2>

<font color='#808080'>
    
Image translation is the process of shifting an image in horizontal and vertical directions. Using image translation we can move our image on the x and y axis by a specified amount.

To perform image translation, a translation matrix is applied to the image that maps the original coordinates to the new, shifted coordinates. Image translations can be performed by applying affine transformations to an input image.
We use the ```cv2.warpAffine``` function in OpenCV to apply affine transformations:
```python
cv2.warpAffine(src, M, dsize, dst, flags=INTER_LINEAR,borderMode=BORDER_CONSTANT, borderValue=0)
```
__Parameters:__

* ```src:``` The source image on which transformations will be applied.
* ```M:``` The transformation matrix.
* ```dsize:``` Size of the output image.
* ```dst:``` dst is an optional output image that stores the result of transformation. The dst image must be of the same size and type as the input image src. If the dst image is not provided, the OpenCV function will create an output image of the same size and type as the input image and return it as the output.
* ```Flags:``` It is an optional parameter that specifies the interpolation method to be used.
* ```borderMode:``` This specifies how to handle the pixels that fall outside the image boundaries. It is a with default value as ```cv2.BORDER_CONSTANT```.
* ```borderValue:``` This is used only with ```cv2.BORDER_CONSTANT``` mode and specifies the constant value used to pad the image. It is an with default value as 0.


In [1]:
import cv2
import numpy as np
img = cv2.imread('imgs/fruits.png')
# Define the translation matrix
tx = 50 # x-direction
ty = 100 # y-direction
M = np.float32([[1, 0, tx], [0, 1, ty]])
# Apply the translation to the image
rows, cols, _ = img.shape
translated_img = cv2.warpAffine(img, M, (cols, rows))
cv2.imshow('Original Image', img)
cv2.imshow('Translated Image', translated_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.2. Rotation <a id='Rotation'></a></h2>

<font color='#808080'>
    
Image rotation is the process of rotating an image by an angle around its center point.There are two ways to perform image rotation:

1. ```cv2.rotate```function for image rotation. this function is that it can __only__ rotate the image by ```90 degrees in a clockwise or anticlockwise direction```. It does __not__ allow us to choose an arbitrary angle to rotate the image.
```python
cv2.rotate(src, rotateCode, dst)
```
__Parameters:__

* ```src:``` The source image on which transformations will be applied.
* ```rotateCode:``` This parameter specifies the direction and angle in which the image should be rotated. The possible values for rotateCode are:
- ```cv2.ROTATE_90_CLOCKWISE:``` Rotates the image 90 degrees in clockwise direction.
- ```cv2.ROTATE_90_COUNTERCLOCKWISE:``` Rotates the image 90 degrees in counter clockwise direction.
- ```cv2.ROTATE_180:``` Rotates the image by 180 degrees.
* ```dst:``` dst is an optional output image that stores the result of transformation.

2. using the ```cv2.warpAffine``` function: We use another function, ```cv2.getRotationMatrix2D```, to generate the rotation matrix used with the cv2.warpAffine function.
```python
cv2.getRotationMatrix2D(center = None, angle, scale = 1)
```
__Parameters:__

* ```center:``` The center point(x,y) of the image rotation. The default value for is None. If a point is not specified, the function will use the center point of the image.
* ```angle:``` The angle of rotation in degrees. Positive values indicate counter-clockwise direction, while negative values correspond to clockwise rotation.
* ```scale:``` The scale parameters is used to scale the size of the image by a factor. The default value for in 1, which means the output image is the same as the size of the input image.


In [2]:
rot_img_90cw = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE) # Rotate clockwise by 90 degrees
rot_img_90ccw = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE) # Rotate counterclockwise by 90 degrees
rot_img_180 = cv2.rotate(img, cv2.ROTATE_180) # Rotate by 180 degrees
cv2.imshow('Original', img)
cv2.imshow('Rotated 90 CW', rot_img_90cw)
cv2.imshow('Rotated 90 CCW', rot_img_90ccw)
cv2.imshow('Rotated 180', rot_img_180)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
rows, cols = img.shape[:2]
# Get rotation matrices.
M1 = cv2.getRotationMatrix2D((100,100), 30, 1)
M2 = cv2.getRotationMatrix2D((cols/2,rows/2), 45, 2)
M3 = cv2.getRotationMatrix2D((cols/2,rows/2), -90, 1)
# Perform rotation
rotated1 = cv2.warpAffine(img, M1, (cols, rows))
rotated2 = cv2.warpAffine(img, M2, (cols, rows))
rotated3 = cv2.warpAffine(img, M3, (cols, rows))
cv2.imshow('Original Image', img)
cv2.imshow('Rotated Image 1', rotated1)
cv2.imshow('Rotated Image 2', rotated2)
cv2.imshow('Rotated Image 3', rotated3)
cv2.waitKey(0)
cv2.destroyAllWindows()

<font color='#808080'>
We have used the scaling factor of 2 for our image. Earlier, we discussed the importance of specifying the output image size in the warpAffine function. In this instance, we set the output picture size to match the size of the input image. To obtain our scaled image, we must replace these numbers with new ones.

## <h2 style="color: blue;"> 1.3.Scaling <a id='Scaling'></a></h2>

<font color='#808080'>
    
Image scaling is a common task in image processing that allows us to resize images according to our requirements. When resizing an image, it is important to maintain the aspect ratio of the image to avoid producing a distorted image.

We use the ```cv2.resize()``` function to resize images using OpenCV:
```python
cv2.resize(src, dst, dsize, fx = 0, fy = 0, interpolation = cv2.INTER_LINEAR)
```
__Parameters:__

* ```src:``` The source image on which transformations will be applied.
* ```dst:``` dst is an optional output image that stores the result of transformation. 
* ```dsize:``` The size of the output image after resizing.
* ```fx:``` The scaling factor along the horizontal axis.
* ```fy:``` The scaling factor along the vertical axis.
If dsize __is not specified__, it will automatically be calculated using the scaling factors fx and fy.
```python
dsize = (int(src.shape[1] * fx), int(src.shape[0] * fy)).
```
* ```interpolation:``` Interpolation refers to the technique used to estimate the new pixel values after applying geometric transformations. Following values can be used for this parameter:
  - ```cv2.INTER_NEAREST:``` nearest neighbor interpolation.
  - ```cv2.INTER_LINEAR:``` bilinear interpolation.
  - ```cv2.INTER_CUBIC:``` bicubic interpolation over 4×4 pixel neighborhood.
  - ```cv2.INTER_AREA:``` resampling using pixel area relation. It is the recommended interpolation method when shrinking an image.
  - ```cv2.INTER_LANCZOS4:``` Lanczos interpolation over 8x8 pixel neighborhood.

In [4]:
resized_img = cv2.resize(img, (0,0), fx = 0.5, fy = 0.5) # Resize the image to half its size
resized_img = cv2.resize(img, (640, 480)) # Resize the image to a specific width and height
cv2.imshow('Original Image', img)
cv2.imshow('Resized Image', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<font color='#808080'>
    
Image scaling can also be implemented using the ```cv2.warpAffine``` function:

In [5]:
new_size = (400, 400) # Define the new size
# Compute the scaling factors for x and y axis
sx = new_size[0]/img.shape[1]
sy = new_size[1]/img.shape[0]
M = np.float32([[sx, 0, 0], [0, sy, 0]]) # Define the transformation matrix
resized_img = cv2.warpAffine(img, M, new_size) # Apply the affine transformation
cv2.imshow('Original Image', img)
cv2.imshow('Resized Image', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.4.Flipping <a id='Flipping'></a></h2>

<font color='#808080'>
    
Image flipping is used to flip an image horizontally or vertically. We can use the ```cv2.flip``` function to implement image flipping:
```python
cv2.flip(src, dst, flipCode = 1)
```
__Parameters:__
* ```src:``` The source image to be flipped
* ```dst:``` Output Variable
* ```flipCode:``` A flag that specifies how to flip the array. The following values can be used with this parameter.
  - ```'0':``` Vertical flip. Image is flipped around the x-axis.
  - ```'1':``` Horizontal flip. Image is flipped around the y-axis
  - ```'-1':``` Image is flipped around both axes
The default value for is 1:

In [6]:
x_flip = cv2.flip(img, 1) # Flip the image horizontally
y_flip = cv2.flip(img, 0)# Flip the image vertically
xy_flip = cv2.flip(img, -1)# Flip the image on both axes
cv2.imshow('Original Image', img)
cv2.imshow('Horizontal flip', x_flip)
cv2.imshow('Vertical flip', y_flip)
cv2.imshow('Both axes', xy_flip)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.5.Shearing <a id='Shearing'></a></h2>

<font color='#808080'>

Image Shearing is a linear transformation that distorts an image along one of its axes. When an image is sheared along the x-axis, the pixels in the image are shifted horizontally. 
We will use the ```cv2.warpAffine``` function to implement image shearing:

In [7]:
# shearing parameters
shear_factor_x = 0.2
shear_factor_y = 0.3
# Obtain shearing matrices
M_x = np.array([[1, shear_factor_x, 0], [0, 1, 0]])
M_y = np.array([[1, 0, 0], [shear_factor_y, 1, 0]])
# Apply shearing transformations
rows, cols = img.shape[:2]
sheared_img_x = cv2.warpAffine(img, M_x, (cols + int(rows * shear_factor_x), rows))
sheared_img_xy = cv2.warpAffine(sheared_img_x, M_y, (cols + int(rows * shear_factor_x), rows + int(cols * shear_factor_y)))
cv2.imshow('Original Image', img)
cv2.imshow('Sheared Image (X axis)', sheared_img_x)
cv2.imshow('Sheared Image (X and Y axis)', sheared_img_xy)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.6.Cropping <a id='Cropping'></a></h2>

<font color='#808080'>

Image cropping is the process of selecting a rectangular portion of an image. Cropping can be considered a type of geometric transformation, where a section of the source image is removed to produce a new image.

In [8]:
# Define ROI coordinates
x1, y1 = 100, 100 # top-left corner
x2, y2 = 300, 400 # bottom-right corner

# Crop image
cropped_img = img[y1:y2, x1:x2]
cv2.imshow('Original Image', img)
cv2.imshow('Cropped Image', cropped_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# <h2 style="color: blue;"> 2.Arithmetic Operations <a id='Arithmetic_Operations'></a></h2>

<font color='#808080'>
Arithmetic operations are a fundamental concept in image processing. These operations involve performing basic mathematical operations on images to generate new images with different properties. These operations are performed on the pixel values and allow us to extract useful information from the images.

## <h2 style="color: blue;"> 2.1.Addition <a id='Addition'></a></h2>

<font color='#808080'>
    
Image addition is a basic arithmetic operation that involves adding pixel values of two or more images to produce a single image.
We use the ```cv2.add()``` function to perform addition using the OpenCV library:
```python
cv2.add(src1, src2, dst, mask, dtype)
```
__Parameters:__

* ```src1 and src2:``` The source images to be added. Both images should be of the same type and size.
* ```dst:``` Output Variable.
* ```mask:``` Masking allows us to choose specific pixels where the operation has to be performed. This is an . If it is left blank, the operation is performed on all the pixels.
* ```dtype:``` The data type of the output. This is an optional parameter that defaults to the input data type if left blank.

In [9]:
import numpy as np
# Initialize two sample 3x3 images
img1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]], dtype = np.uint8)
img2 = np.array([[100, 200, 150], [50, 250, 100], [150, 200, 50]], dtype = np.uint8)
# Add the images
cv2_add = cv2.add(img1, img2)
print('cv2.add() result:\n', cv2_add)
# Add the images using numpy addition
numpy_add = img1 + img2
print('Numpy addition result:\n', numpy_add)

cv2.add() result:
 [[110 220 180]
 [ 90 255 160]
 [220 255 140]]
Numpy addition result:
 [[110 220 180]
 [ 90  44 160]
 [220  24 140]]


### <h2 style="color: blue;"> 2.1.1.weighted addition <a id='weighted_addition'></a></h2>

<font color='#808080'>
    
the weighted addition of images, which means that each image has a different contribution to the final output, and these contributions are not equal, as shared earlier.

We use the ```cv2.addWeighted()``` function for this:
```python
cv2.addWeighted(src1, alpha = 1.0, src2, beta = 0.0, gamma = 0.0, dst, dtype)
```
__Parameters:__

* ```src1 and src2:``` The source images to be added. Both images should be of the same type and size.
* ```alpha:``` Weight of the first image. The range of alpha is 0 to 1, where 0 means the first image will not contribute to the output, and 1 means that the first image will have the maximum contribution to the output. The default value for alpha is 1.
* ```beta:``` Weight of the second image. The range of beta is between 0 and 1, similar to the alpha parameters. The default value for beta is 0.
* ```gamma:``` A scalar value that can be added to all the pixels after the weighted sum is calculated. This is an with default value as 0.
* ```dst:``` Output array.
* ```dtype:``` The data type of the output. This is an optional parameter that defaults to the input data type if left blank.

In [10]:
img1 = cv2.imread('imgs/fruits.png')
img2 = cv2.imread('imgs/fruits.png')
# Add the two images with different weights
result = cv2.addWeighted(img1, 0.7, img2, 0.3, 0)
cv2.imshow('Result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 2.2.Subtraction <a id='Subtraction'></a></h2>

<font color='#808080'>
 
We use the ```cv2.subtract()``` function for image subtraction in OpenCV. This function takes two images as inputs and subtracts the pixel values of the second image from the first image. Any negative values resulting from the subtraction are set to 0, as discussed earlier:
```python
cv2.subtract(src1, src2, dst, mask, dtype)
```
__Parameters:__
* ```src1 and src2:``` The source images to be subtracted. __Both images should be of the same type and size.__ The src2 image is subtracted from src1 image.
* ```dst:``` Output variable.
* ```mask:``` Masking allows us to choose specific pixels where the operation has to be performed. This is an. If it is left blank, the operation is performed on all the pixels.
* ```dtype:``` The data type of the output. This is an optional parameter that defaults to the input data type if left blank.

## <h2 style="color: blue;"> 2.3.Multiplication and division <a id='Multi_division'></a></h2>

<font color='#808080'>
    
Multiplication and division of images involves multiplying/dividing each pixel value of one image with the corresponding pixel value of another image. 
__docimentation:__
```python
cv2.multiply(src1, src2, dst, scale = 1.0, dtype)
cv2.divide(src1, src2, dst, scale = 1.0, dtype)
```
__Parameters:__
* ```src1 and src2:``` The source images to be multiplied or divided.
* ```dst:``` Output variable.
* ```scale:``` The scale factor in __cv2.multiply()__ is a scalar value that is multiplied with the product of the corresponding pixel values of the input images. The scale parameter in __cv2.divide__ is used to divide the numerator (source image) by a scalar value. It is an optional parameter and its default value is 1.0.
* ```dtype:``` The data type of the output. This is an optional parameter that defaults to the input data type if left bank.

### <h2 style="color: blue;"> 2.4.Bitwise operations <a id='Bitwise_operations'></a></h2>

<font color='#808080'>
Bitwise operations can be used to combine two images or to extract and modify specific parts of these images. Bitwise operations, on the other hand, involve manipulating the individual bits of the pixel values in an image. These operations are based on the logical operations of AND, OR, XOR, and NOT.


### <h2 style="color: blue;"> 2.4.1.AND <a id='AND'></a></h2>

<font color='#808080'>
    
Bitwise AND Is a binary operation that takes two images and performs the logical AND operation on them. This operation results in an image where the resultant pixel is 1 only if the corresponding pixel on both images is 1. If any of the bits in the input image is 0, the resulting pixel value is 0.
The syntax for this operation is:
```python
cv2.bitwise_and(src1, src2, dst, mask)
```

### <h2 style="color: blue;"> 2.4.2.OR <a id='OR'></a></h2>

<font color='#808080'>
    
Bitwise OR is a binary operation that takes two images and performs the logical OR operation on them. This operation results in an image where the resultant pixel is 1 if either of the corresponding pixels on both images is 1. If both of the bits on the input images are 0, the resulting pixel value is 0.The syntax for this operation is:
```python
cv2.bitwise_or(src1, src2, dst, mask)
```

### <h2 style="color: blue;"> 2.4.3.XOR <a id='XOR'></a></h2>

<font color='#808080'>
    
Bitwise XOR is a binary operation that takes two images and performs the logical XOR (exclusive OR) operation on them. This operation results in an image where the resultant pixel is 1 if only one of the corresponding pixels on the input images is 1. If both of the bits on the input images are 0 or 1, the resulting pixel value is 0.
The syntax for this operation is:
```python
cv2.bitwise_xor(src1, src2, dst, mask)
```

### <h2 style="color: blue;"> 2.4.4.NOT <a id='NOT'></a></h2>

<font color='#808080'>

Bitwise NOT is a unary operation that takes a single image and performs the logical NOT operation on it. This operation results in an image where all the values of the images are reversed. All pixel values corresponding to 0 are set to 1, and all pixel values corresponding to 1 are set to 0 during the bitwise NOT operation.The syntax for this operation is:
```python
cv2.bitwise_not(src, dst, mask)
```

<font color='#808080'>

the parameters of all bitwise operations is:
__Parameters:__
* ```src1 and src:``` The source images to be used for bitwise operations.
* ```dst:``` Output variable.
* ```mask:``` This is optional mask used to specify which pixels of the input images should be processed. The default value is None, meaning the full image will be used

In [11]:
# Create two black and white images
img1 = np.zeros((400, 400), dtype=np.uint8)
img2 = np.zeros((400, 400), dtype=np.uint8)
# Draw a rectangle on img1
cv2.rectangle(img1, (50, 50), (350, 350), (255, 255, 255), -1)
# Draw a circle on img2
cv2.circle(img2, (200, 200), 150, (255, 255, 255), -1)
# Perform bitwise AND
bitwise_and = cv2.bitwise_and(img1, img2)
# Perform bitwise OR
bitwise_or = cv2.bitwise_or(img1, img2)
# Perform bitwise XOR
bitwise_xor = cv2.bitwise_xor(img1, img2)
# Perform bitwise NOT on img1
bitwise_not = cv2.bitwise_not(img1)
cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('AND', bitwise_and)
cv2.imshow('OR', bitwise_or)
cv2.imshow('XOR', bitwise_xor)
cv2.imshow('NOT of img1', bitwise_not)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 2.5.Channels and color spaces <a id='ChannelsColorCpaces'></a></h2>

<font color='#808080'>
    
In OpenCV, images are represented as a matrix of pixel values. The number of channels in an image is the number of matrices used to represent the image.
1. A ```grayscale``` image has one channel

2. A ```color image``` typically has three channels ```(red, green, and blue)```.
We will discuss the most commonly used color spaces in detail.

### <h2 style="color: blue;"> 2.5.1.Red Green Blue (RGB) color space <a id='RGB'></a></h2>

<font color='#808080'>
    
RGB color space contains red, blue and green channels to represent an image. Each channel in the RGB color space has values ranging from 0 to 255, which describe the intensity of a particular color. A value of 0 represents no color or complete darkness, while a value of 255 represents the maximum intensity or full brightness of that color. here is some examples:
| Color      | RGB Code       | R   | G   | B   |
|------------|----------------|-----|-----|-----|
| Red        | (255,0,0)      | 255 | 0   | 0   |
| Green      | (0,255,0)      | 0   | 255 | 0   |
| Blue       | (0,0,255)      | 0   | 0   | 255 |
| Orange     | (255,165,0)    | 255 | 165 | 0   |
| Brown      | (165,42,42)    | 165 | 42  | 42  |
| Light Gray | (211,211,211)  | 211 | 211 | 211 |
| Dark Gray  | (64,64,64)     | 64  | 64  | 64  |

Let us try to visualize these channels of an image with the help of some code:


In [12]:
img = cv2.imread('imgs/fruits.png')
im1=img.copy()
im2=img.copy()
im3=img.copy()
im1[:,:,0]=0
im1[:,:,1]=0
im2[:,:,2]=0
im2[:,:,1]=0
im3[:,:,2]=0
im3[:,:,0]=0
cv2.imshow('Original Image' , img)
cv2.imshow('Red channel' , im1)
cv2.imshow('Blue channel' , im2)
cv2.imshow('Green channel' , im3)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <h2 style="color: blue;"> 2.5.2.Blue Green Red (BGR) color space <a id='BGR'></a></h2>

<font color='#808080'>
BGR color space is the RGB color space reversed. This is the most commonly used color space in OpenCV. There is no other difference with respect to RGB color space except for the positioning of channels.

### <h2 style="color: blue;"> 2.5.3.Hue Saturation Value (HSV) color space <a id='HSV'></a></h2>

<font color='#808080'>
    
Hue Saturation and Value are the three components of this color space.
* ```Hue:``` Hue refers to the pure color that we perceive.The Hue value ranges from ```0 to 360``` degrees, representing a full circle of colors. __Red is located at 0 degrees, green at 120 degrees, and blue at 240 degrees__.
* ```Saturation:``` Saturation represents the intensity of the color. The saturation value is represented as a percentage from $0%$ to $100%$.
* ```Value:``` Value is the amount of white or black added to the hue. It represents the lightness or the darkness of the color. This is also represented as a percentage, ranging from $0%$ to $100%$.
We will use the cv2.cvtColor function to change the color spaces of an image.
```python
cv2.cvtColor(src, code, dst, dstCn=0)
```
__Parameters:__
* ```src:``` The source image to be converted.
* ```code:``` This represents the type of conversion you want to perform. This parameter defines the current color space of the image and specifies the desired color space to which the image needs to be converted.
  - ```cv2.COLOR_BGR2HSV:``` Converts an image from __BGR__ to __HSV__.
  - ```cv2.COLOR_BGR2GRAY:``` Converts an image from __BGR__ to __grayscale__.
  - ```cv2.COLOR_HSV2BGR:``` Converts an image from __HSV__ to __BGR__.
  - ```cv2.COLOR_BGR2RGB:``` Converts an image from __BGR__ to __RGB__.
* ```dst:``` Output Variable 
* ```dstCn:``` This is the number of channels in the output image. The default value is 0, which matches the number of channels in the input image.

In [13]:
img_bgr = cv2.imread('imgs/fruits.png')
# BGR to grayscale
img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
cv2.imshow('Original Image', img_bgr)
cv2.imshow('Grayscale Image', img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### <h2 style="color: blue;"> 2.5.4.Hue Saturation Lightness (HSL) color space <a id='HSL'></a></h2>

<font color='#808080'>
    
The color space is similar to HSV color space, but there’s a slight difference in how they calculate brightness.
* ```Hue:``` This is similar to the description in the HSV channel.
* ```Saturation:``` This is also similar to the description in the HSV channel.
* ```Lightness:``` Lightness is the measure of how bright or dark the color is, with $0%$ lightness being black and $100%$ lightness being white. This is useful for brightening or darkening images as well as for adding creative touches to them.

### <h2 style="color: blue;"> 2.5.5.LAB color space <a id='LAB'></a></h2>

<font color='#808080'>
    
The LAB color space was designed to resemble the human vision system closely.The LAB color space consists of three dimensions:
* ```L channel (Lightness):``` The L channel represents the lightness dimension.The values are in the range of 0 to 100 where 0 is the lowest brightness(black) and 100 is the brightest (white).
  - ```a channel (Green - Red):``` This defines pure green color on one side and pure red color on the opposite side. The values for this dimension range from __$-128$__ to __$+127$__ and define the color between green to red channels.
  - ```b channel (Blue - Yellow):``` This defines pure blue color on one side and pure red color on the opposite side. The values for this dimension range from __$-128$__ to __$+127$__ and define the color between blue to yellow channels.

### <h2 style="color: blue;"> 2.5.6.YCbCr color space <a id='YCbCr'></a></h2>

<font color='#808080'>
    
The YCbCr color space is a color encoding system that represents colors as a combination of brightness __(luma)__ and two color-difference signals __(chroma)__. 
YCbCr color space is similar to the RGB color space, but it uses luminance (Y), blue-difference (Cb), and red-difference (Cr) components instead of red, green, and blue.
* ```Y channel:``` This channel represents the brightness of the color and is sometimes referred to as the luminance channel.
* ```Cb and Cr channels:``` These channels represent the color information of the image. The Cb channel represents the blue-difference, and the Cr channel represents the red-difference.

### <h2 style="color: blue;"> 2.5.7.Grayscale <a id='Grayscale'></a></h2>

<font color='#808080'>
    
Images in grayscale are represented in a single channel only and contain values from 0 to 255. This value indicated the amount of light on the pixel. In most standard algorithms for converting RGB to grayscale, the red, green, and blue channels are not given equal weights. One common method is to use the formula:

$$ Grayscale = 0.2989 * Red + 0.5870 * Green + 0.1140 * Blue $$