__contents:__

1. [Geometric transformations](#Geometric_transformations)
   * 1.1.[Image translation](#Image_translation)
   * 1.2.[Rotation](#Rotation)
   * 1.3.[Scaling](#Scaling)
   * 1.4.[Flipping](#Flipping)
   * 1.5.[Shearing](#Shearing)
   * 1.6.[Cropping](#Cropping)
2. [Arithmetic Operations](#Arithmetic_Operations)
   * 2.1.[Addition](#Addition)
     - 2.1.1.[weighted addition](#weighted_addition)

# <h2 style="color: blue;"> 1.Geometric transformations <a id='Geometric_transformations'></a></h2>

<font color='#808080'>
In technical terms, image processing involves transforming the coordinates of image points from one coordinate system to another. Using various transformation functions, it is possible to map pixel coordinates in the original image to new coordinates in the transformed image, resulting in different types of transformations.

As we move forward with this chapter, we will explore various image transformation techniques, including rotation, scaling, and more, beginning with image translation.

## <h2 style="color: blue;"> 1.1.Image translation <a id='Image_translation'></a></h2>

<font color='#808080'>
    
Image translation is the process of shifting an image in horizontal and vertical directions. Using image translation we can move our image on the x and y axis by a specified amount.

To perform image translation, a translation matrix is applied to the image that maps the original coordinates to the new, shifted coordinates. Image translations can be performed by applying affine transformations to an input image.
We use the ```cv2.warpAffine``` function in OpenCV to apply affine transformations:
```python
cv2.warpAffine(src, M, dsize, dst, flags=INTER_LINEAR,borderMode=BORDER_CONSTANT, borderValue=0)
```
__Parameters:__

* ```src:``` The source image on which transformations will be applied.
* ```M:``` The transformation matrix.
* ```dsize:``` Size of the output image.
* ```dst:``` dst is an optional output image that stores the result of transformation. The dst image must be of the same size and type as the input image src. If the dst image is not provided, the OpenCV function will create an output image of the same size and type as the input image and return it as the output.
* ```Flags:``` It is an optional parameter that specifies the interpolation method to be used.
* ```borderMode:``` This specifies how to handle the pixels that fall outside the image boundaries. It is a with default value as ```cv2.BORDER_CONSTANT```.
* ```borderValue:``` This is used only with ```cv2.BORDER_CONSTANT``` mode and specifies the constant value used to pad the image. It is an with default value as 0.


In [1]:
import cv2
import numpy as np
img = cv2.imread('fruits.png')
# Define the translation matrix
tx = 50 # x-direction
ty = 100 # y-direction
M = np.float32([[1, 0, tx], [0, 1, ty]])
# Apply the translation to the image
rows, cols, _ = img.shape
translated_img = cv2.warpAffine(img, M, (cols, rows))
cv2.imshow('Original Image', img)
cv2.imshow('Translated Image', translated_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.2. Rotation <a id='Rotation'></a></h2>

<font color='#808080'>
    
Image rotation is the process of rotating an image by an angle around its center point.There are two ways to perform image rotation:

1. ```cv2.rotate```function for image rotation. this function is that it can __only__ rotate the image by ```90 degrees in a clockwise or anticlockwise direction```. It does __not__ allow us to choose an arbitrary angle to rotate the image.
```python
cv2.rotate(src, rotateCode, dst)
```
__Parameters:__

* ```src:``` The source image on which transformations will be applied.
* ```rotateCode:``` This parameter specifies the direction and angle in which the image should be rotated. The possible values for rotateCode are:
- ```cv2.ROTATE_90_CLOCKWISE:``` Rotates the image 90 degrees in clockwise direction.
- ```cv2.ROTATE_90_COUNTERCLOCKWISE:``` Rotates the image 90 degrees in counter clockwise direction.
- ```cv2.ROTATE_180:``` Rotates the image by 180 degrees.
* ```dst:``` dst is an optional output image that stores the result of transformation.

2. using the ```cv2.warpAffine``` function: We use another function, ```cv2.getRotationMatrix2D```, to generate the rotation matrix used with the cv2.warpAffine function.
```python
cv2.getRotationMatrix2D(center = None, angle, scale = 1)
```
__Parameters:__

* ```center:``` The center point(x,y) of the image rotation. The default value for is None. If a point is not specified, the function will use the center point of the image.
* ```angle:``` The angle of rotation in degrees. Positive values indicate counter-clockwise direction, while negative values correspond to clockwise rotation.
* ```scale:``` The scale parameters is used to scale the size of the image by a factor. The default value for in 1, which means the output image is the same as the size of the input image.


In [2]:
rot_img_90cw = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE) # Rotate clockwise by 90 degrees
rot_img_90ccw = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE) # Rotate counterclockwise by 90 degrees
rot_img_180 = cv2.rotate(img, cv2.ROTATE_180) # Rotate by 180 degrees
cv2.imshow('Original', img)
cv2.imshow('Rotated 90 CW', rot_img_90cw)
cv2.imshow('Rotated 90 CCW', rot_img_90ccw)
cv2.imshow('Rotated 180', rot_img_180)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
rows, cols = img.shape[:2]
# Get rotation matrices.
M1 = cv2.getRotationMatrix2D((100,100), 30, 1)
M2 = cv2.getRotationMatrix2D((cols/2,rows/2), 45, 2)
M3 = cv2.getRotationMatrix2D((cols/2,rows/2), -90, 1)
# Perform rotation
rotated1 = cv2.warpAffine(img, M1, (cols, rows))
rotated2 = cv2.warpAffine(img, M2, (cols, rows))
rotated3 = cv2.warpAffine(img, M3, (cols, rows))
cv2.imshow('Original Image', img)
cv2.imshow('Rotated Image 1', rotated1)
cv2.imshow('Rotated Image 2', rotated2)
cv2.imshow('Rotated Image 3', rotated3)
cv2.waitKey(0)
cv2.destroyAllWindows()

<font color='#808080'>
We have used the scaling factor of 2 for our image. Earlier, we discussed the importance of specifying the output image size in the warpAffine function. In this instance, we set the output picture size to match the size of the input image. To obtain our scaled image, we must replace these numbers with new ones.

## <h2 style="color: blue;"> 1.3.Scaling <a id='Scaling'></a></h2>

<font color='#808080'>
    
Image scaling is a common task in image processing that allows us to resize images according to our requirements. When resizing an image, it is important to maintain the aspect ratio of the image to avoid producing a distorted image.

We use the ```cv2.resize()``` function to resize images using OpenCV:
```python
cv2.resize(src, dst, dsize, fx = 0, fy = 0, interpolation = cv2.INTER_LINEAR)
```
__Parameters:__

* ```src:``` The source image on which transformations will be applied.
* ```dst:``` dst is an optional output image that stores the result of transformation. 
* ```dsize:``` The size of the output image after resizing.
* ```fx:``` The scaling factor along the horizontal axis.
* ```fy:``` The scaling factor along the vertical axis.
If dsize __is not specified__, it will automatically be calculated using the scaling factors fx and fy.
```python
dsize = (int(src.shape[1] * fx), int(src.shape[0] * fy)).
```
* ```interpolation:``` Interpolation refers to the technique used to estimate the new pixel values after applying geometric transformations. Following values can be used for this parameter:
  - ```cv2.INTER_NEAREST:``` nearest neighbor interpolation.
  - ```cv2.INTER_LINEAR:``` bilinear interpolation.
  - ```cv2.INTER_CUBIC:``` bicubic interpolation over 4×4 pixel neighborhood.
  - ```cv2.INTER_AREA:``` resampling using pixel area relation. It is the recommended interpolation method when shrinking an image.
  - ```cv2.INTER_LANCZOS4:``` Lanczos interpolation over 8x8 pixel neighborhood.

In [5]:
resized_img = cv2.resize(img, (0,0), fx = 0.5, fy = 0.5) # Resize the image to half its size
resized_img = cv2.resize(img, (640, 480)) # Resize the image to a specific width and height
cv2.imshow('Original Image', img)
cv2.imshow('Resized Image', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<font color='#808080'>
    
Image scaling can also be implemented using the ```cv2.warpAffine``` function:

In [7]:
new_size = (400, 400) # Define the new size
# Compute the scaling factors for x and y axis
sx = new_size[0]/img.shape[1]
sy = new_size[1]/img.shape[0]
M = np.float32([[sx, 0, 0], [0, sy, 0]]) # Define the transformation matrix
resized_img = cv2.warpAffine(img, M, new_size) # Apply the affine transformation
cv2.imshow('Original Image', img)
cv2.imshow('Resized Image', resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.4.Flipping <a id='Flipping'></a></h2>

<font color='#808080'>
    
Image flipping is used to flip an image horizontally or vertically. We can use the ```cv2.flip``` function to implement image flipping:
```python
cv2.flip(src, dst, flipCode = 1)
```
__Parameters:__
* ```src:``` The source image to be flipped
* ```dst:``` Output Variable
* ```flipCode:``` A flag that specifies how to flip the array. The following values can be used with this parameter.
  - ```'0':``` Vertical flip. Image is flipped around the x-axis.
  - ```'1':``` Horizontal flip. Image is flipped around the y-axis
  - ```'-1':``` Image is flipped around both axes
The default value for is 1:

In [8]:
x_flip = cv2.flip(img, 1) # Flip the image horizontally
y_flip = cv2.flip(img, 0)# Flip the image vertically
xy_flip = cv2.flip(img, -1)# Flip the image on both axes
cv2.imshow('Original Image', img)
cv2.imshow('Horizontal flip', x_flip)
cv2.imshow('Vertical flip', y_flip)
cv2.imshow('Both axes', xy_flip)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.5.Shearing <a id='Shearing'></a></h2>

<font color='#808080'>

Image Shearing is a linear transformation that distorts an image along one of its axes. When an image is sheared along the x-axis, the pixels in the image are shifted horizontally. 
We will use the ```cv2.warpAffine``` function to implement image shearing:

In [9]:
# shearing parameters
shear_factor_x = 0.2
shear_factor_y = 0.3
# Obtain shearing matrices
M_x = np.array([[1, shear_factor_x, 0], [0, 1, 0]])
M_y = np.array([[1, 0, 0], [shear_factor_y, 1, 0]])
# Apply shearing transformations
rows, cols = img.shape[:2]
sheared_img_x = cv2.warpAffine(img, M_x, (cols + int(rows * shear_factor_x), rows))
sheared_img_xy = cv2.warpAffine(sheared_img_x, M_y, (cols + int(rows * shear_factor_x), rows + int(cols * shear_factor_y)))
cv2.imshow('Original Image', img)
cv2.imshow('Sheared Image (X axis)', sheared_img_x)
cv2.imshow('Sheared Image (X and Y axis)', sheared_img_xy)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <h2 style="color: blue;"> 1.6.Cropping <a id='Cropping'></a></h2>

<font color='#808080'>

Image cropping is the process of selecting a rectangular portion of an image. Cropping can be considered a type of geometric transformation, where a section of the source image is removed to produce a new image.

In [10]:
# Define ROI coordinates
x1, y1 = 100, 100 # top-left corner
x2, y2 = 300, 400 # bottom-right corner

# Crop image
cropped_img = img[y1:y2, x1:x2]
cv2.imshow('Original Image', img)
cv2.imshow('Cropped Image', cropped_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# <h2 style="color: blue;"> 2.Arithmetic Operations <a id='Arithmetic_Operations'></a></h2>

<font color='#808080'>
Arithmetic operations are a fundamental concept in image processing. These operations involve performing basic mathematical operations on images to generate new images with different properties. These operations are performed on the pixel values and allow us to extract useful information from the images.

## <h2 style="color: blue;"> 2.1.Addition <a id='Addition'></a></h2>

<font color='#808080'>
    
Image addition is a basic arithmetic operation that involves adding pixel values of two or more images to produce a single image.
We use the ```cv2.add()``` function to perform addition using the OpenCV library:
```python
cv2.add(src1, src2, dst, mask, dtype)
```
__Parameters:__

* ```src1 and src2:``` The source images to be added. Both images should be of the same type and size.
* ```dst:``` Output Variable.
* ```mask:``` Masking allows us to choose specific pixels where the operation has to be performed. This is an . If it is left blank, the operation is performed on all the pixels.
* ```dtype:``` The data type of the output. This is an optional parameter that defaults to the input data type if left blank.

In [11]:
import numpy as np
# Initialize two sample 3x3 images
img1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]], dtype = np.uint8)
img2 = np.array([[100, 200, 150], [50, 250, 100], [150, 200, 50]], dtype = np.uint8)
# Add the images
cv2_add = cv2.add(img1, img2)
print('cv2.add() result:\n', cv2_add)
# Add the images using numpy addition
numpy_add = img1 + img2
print('Numpy addition result:\n', numpy_add)

cv2.add() result:
 [[110 220 180]
 [ 90 255 160]
 [220 255 140]]
Numpy addition result:
 [[110 220 180]
 [ 90  44 160]
 [220  24 140]]


### <h2 style="color: blue;"> 2.1.1.weighted addition <a id='weighted_addition'></a></h2>

<font color='#808080'>
    
the weighted addition of images, which means that each image has a different contribution to the final output, and these contributions are not equal, as shared earlier.

We use the ```cv2.addWeighted()``` function for this:
```python
cv2.addWeighted(src1, alpha = 1.0, src2, beta = 0.0, gamma = 0.0, dst, dtype)
```
__Parameters:__

* ```src1 and src2:``` The source images to be added. Both images should be of the same type and size.
* ```alpha:``` Weight of the first image. The range of alpha is 0 to 1, where 0 means the first image will not contribute to the output, and 1 means that the first image will have the maximum contribution to the output. The default value for alpha is 1.
* ```beta:``` Weight of the second image. The range of beta is between 0 and 1, similar to the alpha parameters. The default value for beta is 0.
* ```gamma:``` A scalar value that can be added to all the pixels after the weighted sum is calculated. This is an with default value as 0.
* ```dst:``` Output array.
* ```dtype:``` The data type of the output. This is an optional parameter that defaults to the input data type if left blank.

In [14]:
img1 = cv2.imread('fruits.png')
img2 = cv2.imread('fruits.png')
# Add the two images with different weights
result = cv2.addWeighted(img1, 0.7, img2, 0.3, 0)
cv2.imshow('Result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()