In [1]:
import cv2

In [12]:
img = cv2.imread("HappyFish.jpg", cv2.IMREAD_COLOR)

In [28]:
print(img.shape[2])

3


In [25]:
cv2.imshow("fish", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
img[100,150,2]

130

In [42]:
for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        if j%10 == 0:
            img[i,j] = [42,52,100]

cv2.imshow("fish", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
img_roi = img[30:170, 40:150]
cv2.imshow("fish_roi", img_roi)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [48]:
import numpy as np
img_base = np.zeros((500,500,3), dtype = np.uint8)
p1 = (170 , 250)
p2 = (250 , 50)
p3 = (300 , 250)

cv2.line(img_base, p1, p2, (52, 100, 32), 2)
cv2.line(img_base, p2, p3, (100, 100, 0), 10)
cv2.line(img_base, p3, p1, (21, 10, 200), 20)



array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [49]:
cv2.imshow("triangle", img_base)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [55]:
img2 = np.zeros((600,600,3), dtype = np.uint8)
cv2.rectangle(img2, (150,250), (350,400), (22,150,100), thickness = -1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [56]:
cv2.imshow("rectangle", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
img3 = np.zeros((600,600,3), dtype = np.uint8)
cv2.circle(img3, (250,250), 50, (0,0,255), thickness = -1)
cv2.circle(img3, (250,250), 100, (0,255,0),  thickness = 5)
cv2.circle(img3, (250,250), 150, (255,0,0),  thickness = 10)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [64]:
text = "Hello world"
cv2.putText(img3, text, (200, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, (255, 0, 100), 3)
cv2.imshow("circle", img3)
cv2.waitKey(0)
cv2.destroyAllWindows()